nome = input('Qual é seu nome? ')
print('Prazer em te conhecer {}!'.format(nome))
print('Prazer em te conhecer {:>10}!'.format(nome))
print('Prazer em te conhecer {:<10}!'.format(nome))
print('Prazer em te conhecer {:=^10}!'.format(nome))
print('Prazer em te conhecer {:^10}!'.format(nome))